name: My first work flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DAY_OF_WEEK: MONDAY
  testvar: value-1

jobs:
  build:
    name: "print variable"
#    needs: helloworld2
    runs-on: ubuntu-latest
    env:
      path: $GITHUB_WORKSPACE
    steps:
#      This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "Build statring "
        run: |
          pwd
          ls -a
          echo "workdir ${{env.path}}"
          echo "today is $DAY_OF_WEEK"
          echo "a=testvar ${{env.testvar}}" >> $GITHUB_ENV
      - name: "build end"
        run: |
          echo "${{env.a}}"
#  helloworld2:
#    runs-on: ubuntu-latest
#    steps:
#      - name: "second message"
#        run: echo "bye deepak"