name: My first work flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  helloworld:
    needs: helloworld2
    runs-on: ubuntu-latest
    steps:
      - name: "print message"
        run: echo "Hi deepak"
  helloworld2:
    runs-on: ubuntu-latest
    steps:
      - name: "second message"
        run: echo "bye deepak"