name: My first work flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
#    needs: helloworld2
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "print message"
        run: |
          pwd
          ls -a
          echo $GITHUB_WORKSPACE
#  helloworld2:
#    runs-on: ubuntu-latest
#    steps:
#      - name: "second message"
#        run: echo "bye deepak"